"""
Utils Package
Utility modules for the bot.
"""
from src.utils.decorators import (
    cached,
    log_calls,
    rate_limit,
    require_owner,
    require_private_chat,
    retry,
    singleton,
    timing,
)
from src.utils.formatting import (
    fmt_bb_position,
    fmt_int,
    fmt_macd_trend,
    fmt_mcap,
    fmt_number,
    fmt_obv_trend,
    fmt_pct,
    fmt_price,
    fmt_price_int,
    fmt_ratio,
    fmt_rsi_zone,
    fmt_signed,
    fmt_stoch_signal,
    fmt_trend_strength,
    fmt_tv_rating,
    fmt_vol_signal,
    fmt_volume,
    format_table_header,
    format_table_row,
)
from src.utils.helpers import (
    chunk_list,
    deep_update,
    filter_none_values,
    flatten_dict,
    format_date,
    format_datetime,
    generate_hash,
    get_nested,
    json_dumps_safe,
    load_json_safe,
    merge_dicts,
    parse_bool,
    safe_get,
    save_json_safe,
    set_nested,
    split_text,
    truncate_text,
)
from src.utils.time_utils import (
    format_ist,
    get_market_schedule,
    is_market_hours,
    is_pre_market,
    is_trading_day,
    next_trading_day,
    now_ist,
    previous_trading_day,
    today_ist,
)
from src.utils.validators import (
    ValidationError,
    sanitize_symbol,
    sanitize_text,
    validate_chat_id,
    validate_date,
    validate_email,
    validate_symbol,
    validate_time_str,
)

__all__ = [
    # Time utils
    "now_ist",
    "today_ist",
    "is_market_hours",
    "is_pre_market",
    "is_trading_day",
    "next_trading_day",
    "previous_trading_day",
    "format_ist",
    "get_market_schedule",

    # Formatting
    "fmt_price",
    "fmt_price_int",
    "fmt_number",
    "fmt_int",
    "fmt_pct",
    "fmt_signed",
    "fmt_mcap",
    "fmt_volume",
    "fmt_ratio",
    "fmt_vol_signal",
    "fmt_rsi_zone",
    "fmt_trend_strength",
    "fmt_macd_trend",
    "fmt_bb_position",
    "fmt_obv_trend",
    "fmt_tv_rating",
    "fmt_stoch_signal",
    "format_table_row",
    "format_table_header",

    # Validators
    "validate_symbol",
    "validate_date",
    "validate_chat_id",
    "validate_email",
    "validate_time_str",
    "sanitize_symbol",
    "sanitize_text",
    "ValidationError",

    # Decorators
    "log_calls",
    "timing",
    "retry",
    "singleton",
    "cached",
    "require_owner",
    "require_private_chat",
    "rate_limit",

    # Helpers
    "generate_hash",
    "safe_get",
    "chunk_list",
    "flatten_dict",
    "merge_dicts",
    "filter_none_values",
    "truncate_text",
    "split_text",
    "format_datetime",
    "format_date",
    "parse_bool",
    "get_nested",
    "set_nested",
    "deep_update",
    "json_dumps_safe",
    "load_json_safe",
    "save_json_safe",
]
